name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependencias
        run: dotnet restore test1.sln

      - name: Ejecutar pruebas
        run: dotnet test test1.sln --no-build --verbosity normal
